### ISSUE TITLE
Question(s)

### ISSUE THREAD

**Issue by Fireworkstars46** [FilUnderscore/ModManager#10]
Would this mod would allow me to disable/enable mods from the main menu?

**Comment by FilUnderscore** [comment]
Yes, but you would still need to restart the game due to how mods are loaded on startup. You can enable/disable mods in the Mods menu by clicking on individual mods and unticking the Enabled box.

**Comment by Fireworkstars46** [comment]
So I can't have it work without restarting the game?

**Comment by FilUnderscore** [comment]
No, because the game loads some mod assets on startup which cannot be unloaded without restarting the game and preventing the mods from loading.

**Comment by Fireworkstars46** [comment]
Also if I create a world with only the backup mod and after it was created I add this mod to it, would my world have issues/get corrupted etc or no?

**Comment by FilUnderscore** [comment]
No, there should be no issues with adding/removing this mod with an existing world. This mod mainly modifies the main menu and a few elements of the in-game UI (e.g. error popups).

**Comment by Fireworkstars46** [comment]
Also is this mod required for other mods to download if they have the non manual download? Like the lawn tractor mod has this option (image).![image](https://github.com/FilUnderscore/ModManager/assets/30112538/524cee81-dda9-4fd2-a764-f948854ff0f8)

**Comment by FilUnderscore** [comment]
That is referring to the Nexus Mod Manager, not related to this mod.

**Comment by Fireworkstars46** [comment]
So it's a different thing?

**Comment by FilUnderscore** [comment]
Yes.

**Comment by Fireworkstars46** [comment]
Also for the A21 one, is it on the main files section or on the old files section?

**Comment by FilUnderscore** [comment]
The A21 will be listed under the Old Files section, each entries should list the version they support in the description when you click to expand them individually.
