### ISSUE TITLE
bug on a21b16

### ISSUE THREAD

**Issue by woshigenm** [FilUnderscore/ModManager#8]
When i open the mods page in the game, the all mods shows disable, but in fact they can run
![image](https://github.com/FilUnderscore/ModManager/assets/99122353/cd773213-945b-48e4-9087-da1bfe3c88dd)
[output_log_client__2023-10-04__03-10-40.txt](https://github.com/FilUnderscore/ModManager/files/12796207/output_log_client__2023-10-04__03-10-40.txt)

**Comment by FilUnderscore** [comment]
Thanks for reporting this - I've encountered this one a couple of times but never been able to properly replicate it and haven't come across it recently in testing.

It appears to be a visual bug from what I've seen and may prevent you from disabling mods. I'll look into getting a fix out.

**Comment by FilUnderscore** [comment]
1.1.1 should include a fix for this issue as there have been some changes to the mod loader code. If you still continue to experience this issue after updating, please feel free to re-open this issue. Thanks.
